//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgs.Persistance.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGSEntities : DbContext
    {
        public SGSEntities()
            : base("name=SGSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbCours> tbCours { get; set; }
        public virtual DbSet<tbEnseignants> tbEnseignants { get; set; }
        public virtual DbSet<tbEtudiants> tbEtudiants { get; set; }
        public virtual DbSet<tbFormations> tbFormations { get; set; }
        public virtual DbSet<tbSessions> tbSessions { get; set; }
    }
}
